from pydantic import BaseModel, Field, EmailStr, ConfigDict
from typing import Optional, List
from datetime import date
from decimal import Decimal

class OwnerDetailsSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)
    
    owner_name: Optional[str] = Field(None, alias="ownerName")
    date_of_birth: Optional[date] = Field(None, alias="dateOfBirth")
    gender: Optional[str] = None
    aadhaar_number: Optional[str] = Field(None, alias="aadhaarNumber")
    pan_number: Optional[str] = Field(None, alias="panNumber")
    profile_photo_url: Optional[str] = Field(None, alias="profilePhotoUrl")
    mobile: Optional[str] = Field(None, alias="contactNumber")
    email_id: Optional[EmailStr] = Field(None, alias="emailId")
    address_line1: Optional[str] = Field(None, alias="addressLine1")
    address_line2: Optional[str] = Field(None, alias="addressLine2")
    owner_city: Optional[str] = Field(None, alias="ownerCity")
    owner_district: Optional[str] = Field(None, alias="ownerDistrict")
    owner_state: Optional[str] = Field(None, alias="ownerState")
    owner_pin_code: Optional[str] = Field(None, alias="ownerPinCode")
    preferred_contact_method: Optional[List[str]] = Field(default=[], alias="preferredContactMethod")
    preferred_contact_time: Optional[str] = Field(None, alias="preferredContactTime")
    bank_name: Optional[str] = Field(None, alias="bankName")
    account_holder_name: Optional[str] = Field(None, alias="accountHolderName")
    account_number: Optional[str] = Field(None, alias="accountNumber")
    ifsc_code: Optional[str] = Field(None, alias="ifscCode")
    upi_id: Optional[str] = Field(None, alias="upiId")
    additionalnote: Optional[str] = Field(None, alias="additionalNote")

class AgentDetailsSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)
    
    agent_name: Optional[str] = Field(None, alias="agentName")
    date_of_birth: Optional[date] = Field(None, alias="agentDateOfBirth")
    gender: Optional[str] = Field(None, alias="agentGender")
    profile_photo_url: Optional[str] = Field(None, alias="profilePhotoUrl")
    agency_logo_url: Optional[str] = Field(None, alias="agencyLogo")
    mobile: Optional[str] = Field(None, alias="mobileNumber")
    email_id: Optional[EmailStr] = Field(None, alias="agentEmail")
    office_address: Optional[str] = Field(None, alias="officeAddress")
    agency_name: Optional[str] = Field(None, alias="agencyName")
    rera_registration_number: Optional[str] = Field(None, alias="reraNumber")
    gst_number: Optional[str] = Field(None, alias="gstNumber")
    experience: Optional[int] = Field(None, alias="yearsExperience")
    active_listing: Optional[int] = Field(None, alias="activeListings")
    service_area: Optional[List[str]] = Field(default=[], alias="serviceAreas")
    website: Optional[str] = None
    facebook: Optional[str] = None
    instagram: Optional[str] = None
    linkedin: Optional[str] = None
    youtube: Optional[str] = None
    bank_name: Optional[str] = Field(None, alias="bankName")
    account_holder_name: Optional[str] = Field(None, alias="accountHolderName")
    account_number: Optional[str] = Field(None, alias="accountNumber")
    ifsc_code: Optional[str] = Field(None, alias="ifscCode")
    upi_id: Optional[str] = Field(None, alias="upiId")

class BuilderDetailsSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)
    
    name: Optional[str] = Field(None, alias="builderName")
    designation: Optional[str] = None
    mobile: Optional[str] = Field(None, alias="builderMobile")
    whatsapp_number: Optional[str] = Field(None, alias="whatsappNumber")
    email: Optional[EmailStr] = Field(None, alias="builderEmail")
    rera_registration_number: Optional[str] = Field(None, alias="builderReraNumber")
    gst_number: Optional[str] = Field(None, alias="builderGstNumber")
    experience: Optional[int] = Field(None, alias="builderExperience")
    aadhar_number: Optional[str] = Field(None, alias="builderAadhaar")
    pan_number: Optional[str] = Field(None, alias="builderPan")
    profile_photo_url: Optional[str] = Field(None, alias="profilePhotoUrl")
    company_logo_url: Optional[str] = Field(None, alias="companyLogo")
    company_name: Optional[str] = Field(None, alias="companyName")
    company_reg_number: Optional[str] = Field(None, alias="companyRegNumber")
    company_website: Optional[str] = Field(None, alias="companyWebsite")
    company_description: Optional[str] = Field(None, alias="companyDescription")
    office_address: Optional[str] = Field(None, alias="builderOfficeAddress")
    city: Optional[str] = Field(None, alias="builderCity")
    district: Optional[str] = Field(None, alias="builderDistrict")
    state: Optional[str] = Field(None, alias="builderState")
    pincode: Optional[str] = Field(None, alias="builderPincode")
    landmark: Optional[str] = Field(None, alias="builderLandmark")
    website: Optional[str] = Field(None, alias="builderWebsite")
    facebook: Optional[str] = Field(None, alias="builderFacebook")
    instagram: Optional[str] = Field(None, alias="builderInstagram")
    linkedin: Optional[str] = Field(None, alias="builderLinkedin")
    youtube: Optional[str] = Field(None, alias="builderYoutube")
    bank_name: Optional[str] = Field(None, alias="bankName")
    account_holder_name: Optional[str] = Field(None, alias="accountHolderName")
    account_number: Optional[str] = Field(None, alias="accountNumber")
    ifsc_code: Optional[str] = Field(None, alias="ifscCode")
    upi_id: Optional[str] = Field(None, alias="upiId")

class PMDetailsSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)
    
    name: Optional[str] = Field(None, alias="pmName")
    designation: Optional[str] = Field(None, alias="pmDesignation")
    mobile: Optional[str] = Field(None, alias="pmMobile")
    whatsapp_number: Optional[str] = Field(None, alias="pmWhatsapp")
    email: Optional[EmailStr] = Field(None, alias="pmEmail")
    rera_registration_number: Optional[str] = Field(None, alias="pmReraNumber")
    gst_number: Optional[str] = Field(None, alias="pmGstNumber")
    experience: Optional[int] = Field(None, alias="pmExperience")
    aadhar_number: Optional[str] = Field(None, alias="pmAadhaar")
    pan_number: Optional[str] = Field(None, alias="pmPan")
    profile_photo_url: Optional[str] = Field(None, alias="profilePhotoUrl")
    company_logo_url: Optional[str] = Field(None, alias="companyLogo")
    company_name: Optional[str] = Field(None, alias="pmCompanyName")
    company_reg_number: Optional[str] = Field(None, alias="pmCompanyRegNumber")
    company_website: Optional[str] = Field(None, alias="pmCompanyWebsite")
    company_description: Optional[str] = Field(None, alias="pmCompanyDescription")
    office_address: Optional[str] = Field(None, alias="pmOfficeAddress")
    city: Optional[str] = Field(None, alias="pmCity")
    district: Optional[str] = Field(None, alias="pmDistrict")
    state: Optional[str] = Field(None, alias="pmState")
    pincode: Optional[str] = Field(None, alias="pmPincode")
    landmark: Optional[str] = Field(None, alias="pmLandmark")
    website: Optional[str] = Field(None, alias="pmWebsite")
    facebook: Optional[str] = Field(None, alias="pmFacebook")
    instagram: Optional[str] = Field(None, alias="pmInstagram")
    linkedin: Optional[str] = Field(None, alias="pmLinkedin")
    youtube: Optional[str] = Field(None, alias="pmYoutube")
    bank_name: Optional[str] = Field(None, alias="bankName")
    account_holder_name: Optional[str] = Field(None, alias="accountHolderName")
    account_number: Optional[str] = Field(None, alias="accountNumber")
    ifsc_code: Optional[str] = Field(None, alias="ifscCode")
    upi_id: Optional[str] = Field(None, alias="upiId")